name: Testing

on: push

jobs:
  test:
    name: Tests passes
    runs-on: ubuntu-latest
    env:
      VITE_API_URL: ${{secrets.VITE_API_URL}})

    steps:
      - name: ⬇ Git checkout
        uses: actions/checkout@v3

      - name: 💾 Install modules
        run: npm ci

      - name: 🧪 Testing
        run: npm test
